# Site settings
title: Andres Galante
email: a@andresgalante.com
description: > # this means to ignore newlines until "baseurl:"
  This is Andrés Galantes personal blog. Cyclist, dad, designer, diver, entrepreneur, frontend coder,  guitarist, redhatter, husband and tenis player (in alphabetical order).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andresgalante.github.io" # the base hostname & protocol for your site
twitter_username: andresgalante
github_username:  andresgalante

# Build settings
markdown: kramdown
